import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/db";
import { chatConversations, chatMessages, users } from "@/db/schema";
import { getSession } from "@/lib/auth";

export async function GET(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Log in required."},{status:401});const db=getDb(),requested=Number(new URL(request.url).searchParams.get("conversation")||0);let conversationId=requested;if(session.role==="CUSTOMER"){const [conversation]=await db.select().from(chatConversations).where(eq(chatConversations.customerId,session.userId)).limit(1);conversationId=conversation?.id||0}else if(!["STAFF","ADMIN","SUPER_ADMIN"].includes(session.role))return NextResponse.json({error:"Not allowed."},{status:403});if(!conversationId)return NextResponse.json({messages:[]});const [allowed]=session.role==="CUSTOMER"?await db.select({id:chatConversations.id}).from(chatConversations).where(and(eq(chatConversations.id,conversationId),eq(chatConversations.customerId,session.userId))).limit(1):[{id:conversationId}];if(!allowed)return NextResponse.json({error:"Not found."},{status:404});const messages=await db.select({id:chatMessages.id,message:chatMessages.message,createdAt:chatMessages.createdAt,senderId:chatMessages.senderId,firstName:users.firstName,role:users.role}).from(chatMessages).innerJoin(users,eq(users.id,chatMessages.senderId)).where(eq(chatMessages.conversationId,conversationId)).orderBy(chatMessages.createdAt);return NextResponse.json({conversationId,messages})}

export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Log in required."},{status:401});const parsed=z.object({message:z.string().trim().min(1).max(2000),conversationId:z.number().int().positive().optional()}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Write a message first."},{status:400});const db=getDb();let conversationId=parsed.data.conversationId;if(session.role==="CUSTOMER"){const [existing]=await db.select().from(chatConversations).where(eq(chatConversations.customerId,session.userId)).limit(1);if(existing)conversationId=existing.id;else{const [created]=await db.insert(chatConversations).values({customerId:session.userId});conversationId=created.insertId}}else if(!conversationId||!["STAFF","ADMIN","SUPER_ADMIN"].includes(session.role))return NextResponse.json({error:"Conversation required."},{status:400});await db.insert(chatMessages).values({conversationId,senderId:session.userId,message:parsed.data.message});await db.update(chatConversations).set({lastMessageAt:new Date(),status:"OPEN"}).where(eq(chatConversations.id,conversationId));return NextResponse.json({ok:true,conversationId},{status:201})}
