"use client";
import { FormEvent, useMemo, useState } from "react";
import { Building2, Plus, Search, X } from "lucide-react";
import { MapPicker, type PinnedLocation } from "../../map-picker";
type Store={id:number;name:string;code:string;phone:string;email:string|null;address:string;latitude:string|null;longitude:string|null;openingHours:Record<string,string>|null;deliveryAreas:string[]|null;isActive:boolean};
export function StoreManager({initialStores}:{initialStores:Store[]}){
 const[rows,setRows]=useState(initialStores),[query,setQuery]=useState(""),[editing,setEditing]=useState<Store|"new"|null>(null),[saving,setSaving]=useState<number|"new"|null>(null),[error,setError]=useState("");
 // Delivery is priced from this pin, so it is captured on a map rather than typed.
 const[pin,setPin]=useState<PinnedLocation|null>(null);
 // The editor and its pin open together, so a stored location is never shown against
 // the wrong store while an effect catches up.
 function openEditor(store:Store|"new"|null){setEditing(store);const row=store==="new"?null:store;setPin(row?.latitude&&row.longitude?{latitude:Number(row.latitude),longitude:Number(row.longitude),address:row.address}:null)}
 const shown=useMemo(()=>rows.filter(row=>`${row.name} ${row.code} ${row.address}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const form=new FormData(event.currentTarget),hours=String(form.get("openingHours")||"").trim(),payload={name:String(form.get("name")),code:String(form.get("code")),phone:String(form.get("phone")),email:String(form.get("email")||""),address:String(form.get("address")),latitude:pin?.latitude??null,longitude:pin?.longitude??null,openingHours:hours?{General:hours}:null,deliveryAreas:String(form.get("deliveryAreas")||"").split(",").map(value=>value.trim()).filter(Boolean),isActive:form.get("isActive")==="on"},isNew=editing==="new",id=isNew?"new":editing.id;setSaving(id);setError("");try{const response=await fetch(isNew?"/api/stores":`/api/stores/${id}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)return setError(data.error||"Store could not be saved.");if(isNew)setRows(current=>[{...payload,id:data.id,latitude:payload.latitude?.toString()||null,longitude:payload.longitude?.toString()||null},...current]);else setRows(current=>current.map(row=>row.id===id?{...row,...payload,latitude:payload.latitude?.toString()||null,longitude:payload.longitude?.toString()||null}:row));openEditor(null)}finally{setSaving(null)}}
 const current=editing==="new"?null:editing;
 return <main className="compact-admin-page"><header><div><a href="/admin">← Dashboard</a><h1>Stores</h1><p>Every active store automatically receives an indexable pharmacy page.</p></div><button onClick={()=>openEditor("new")}><Plus/> Add store</button></header><div className="compact-table-tools"><label><Search/><input placeholder="Search store, code or address" value={query} onChange={event=>setQuery(event.target.value)}/></label><span>{shown.length} stores</span></div><div className="compact-table"><div className="compact-table-head manager-row"><span>Store</span><span>Code</span><span>Phone</span><span>Address</span><span>Status</span></div>{shown.map(row=><div className={`compact-table-row manager-row ${saving===row.id?"row-saving":""}`} key={row.id}><span><Building2/><button className="row-link" onClick={()=>openEditor(row)}>{row.name}</button></span><b>{row.code}</b><a href={`tel:${row.phone}`}>{row.phone}</a><span>{row.address}</span><span className={row.isActive?"status-active":"status-inactive"}>{saving===row.id?"Saving…":row.isActive?"Active":"Inactive"}</span></div>)}</div>
 {editing&&<div className="product-modal" onClick={()=>openEditor(null)}><form onSubmit={save} onClick={event=>event.stopPropagation()}><header><div><h2>{editing==="new"?"Add store":"Edit store"}</h2><p>The public location page and sitemap update automatically.</p></div><button type="button" onClick={()=>openEditor(null)}><X/></button></header><div className="product-form-grid"><label>Store name<input name="name" defaultValue={current?.name||""} required/></label><label>Store code<input name="code" defaultValue={current?.code||""} required/></label><label>Phone<input name="phone" defaultValue={current?.phone||""} required/></label><label>Email<input type="email" name="email" defaultValue={current?.email||""}/></label><label className="full">Physical address<textarea name="address" defaultValue={current?.address||""} required/></label><div className="full store-pin"><span className="checkout-location-title">Store location</span><p className="checkout-location-note">Delivery distance is measured from this pin, so place it on the shop door rather than the estate.</p><MapPicker value={pin} onChange={setPin} height={220} searchPlaceholder="Search for the shop, road or landmark"/></div><label className="full">Opening hours<input name="openingHours" defaultValue={current?.openingHours?.General||""} placeholder="Mon-Sat 8am-8pm, Sun 9am-6pm"/></label><label className="full">Delivery areas<input name="deliveryAreas" defaultValue={current?.deliveryAreas?.join(", ")||""} placeholder="Juja, JKUAT, Kalimoni"/><small>Separate areas with commas. They appear on the public page.</small></label><label className="check-label"><input type="checkbox" name="isActive" defaultChecked={current?.isActive??true}/> Active and publicly listed</label></div>{error&&<div className="auth-error">{error}</div>}<footer><button type="button" onClick={()=>openEditor(null)}>Cancel</button><button disabled={saving!==null}>{saving?"Saving…":"Save store"}</button></footer></form></div>}</main>;
}
