"use client";
import { FormEvent, useMemo, useState } from "react";
import { Building2, Plus, Search, X } from "lucide-react";
type Store={id:number;name:string;code:string;phone:string;email:string|null;address:string;isActive:boolean};
export function StoreManager({initialStores}:{initialStores:Store[]}){
 const [rows,setRows]=useState(initialStores),[query,setQuery]=useState(""),[editing,setEditing]=useState<Store|"new"|null>(null),[saving,setSaving]=useState<number|"new"|null>(null),[error,setError]=useState("");
 const shown=useMemo(()=>rows.filter(r=>`${r.name} ${r.code} ${r.address}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),payload={name:String(f.get("name")),code:String(f.get("code")),phone:String(f.get("phone")),email:String(f.get("email")||""),address:String(f.get("address")),isActive:f.get("isActive")==="on"},isNew=editing==="new",id=isNew?"new":editing.id;setSaving(id);setError("");try{const res=await fetch(isNew?"/api/stores":`/api/stores/${id}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)return setError(data.error||"Store could not be saved.");if(isNew)setRows(c=>[{...payload,id:data.id},...c]);else setRows(c=>c.map(r=>r.id===id?{...r,...payload}:r));setEditing(null)}finally{setSaving(null)}}
 const current=editing==="new"?null:editing;
 return <main className="compact-admin-page"><header><div><a href="/admin">← Dashboard</a><h1>Stores</h1><p>Branches, contact details and operating status.</p></div><button onClick={()=>setEditing("new")}><Plus/> Add store</button></header><div className="compact-table-tools"><label><Search/><input placeholder="Search store, code or address" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{shown.length} stores</span></div><div className="compact-table"><div className="compact-table-head manager-row"><span>Store</span><span>Code</span><span>Phone</span><span>Address</span><span>Status</span></div>{shown.map(r=><div className={`compact-table-row manager-row ${saving===r.id?"row-saving":""}`} key={r.id}><span><Building2/><button className="row-link" onClick={()=>setEditing(r)}>{r.name}</button></span><b>{r.code}</b><a href={`tel:${r.phone}`}>{r.phone}</a><span>{r.address}</span><span className={r.isActive?"status-active":"status-inactive"}>{saving===r.id?"Saving…":r.isActive?"Active":"Inactive"}</span></div>)}</div>
 {editing&&<div className="product-modal" onClick={()=>setEditing(null)}><form onSubmit={save} onClick={e=>e.stopPropagation()}><header><h2>{editing==="new"?"Add store":"Edit store"}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></header><div className="product-form-grid"><label>Store name<input name="name" defaultValue={current?.name||""} required/></label><label>Store code<input name="code" defaultValue={current?.code||""} required/></label><label>Phone<input name="phone" defaultValue={current?.phone||""} required/></label><label>Email<input type="email" name="email" defaultValue={current?.email||""}/></label><label className="full">Address<textarea name="address" defaultValue={current?.address||""} required/></label><label className="check-label"><input type="checkbox" name="isActive" defaultChecked={current?.isActive??true}/> Active</label></div>{error&&<div className="auth-error">{error}</div>}<footer><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button disabled={saving!==null}>{saving?"Saving…":"Save store"}</button></footer></form></div>}</main>
}
