"use client";
import { ArrowLeft,CheckCircle2,CreditCard,LocateFixed,MapPin,ShoppingCart } from "lucide-react";
import Image from "next/image";
import { FormEvent,useMemo,useState } from "react";
type Product={id:number;name:string;price:string;discountPrice:string|null;packSize:string|null};
type Customer={firstName:string;lastName:string;email:string;phone:string|null}|null;
export function CheckoutForm({initialCart,initialCatalog,customer}:{initialCart:Record<number,number>;initialCatalog:Product[];customer:Customer}){
 const [method,setMethod]=useState<"DELIVERY"|"PICKUP">("DELIVERY"),[error,setError]=useState(""),[complete,setComplete]=useState<{orderNumber:string;total:number}|null>(null),[coordinates,setCoordinates]=useState<{latitude:number;longitude:number}|null>(null),[locating,setLocating]=useState(false);
 const lines=useMemo(()=>Object.entries(initialCart).map(([id,quantity])=>({product:initialCatalog.find(item=>item.id===Number(id)),quantity})).filter(line=>line.product),[initialCart,initialCatalog]),subtotal=lines.reduce((sum,line)=>sum+Number(line.product!.discountPrice??line.product!.price)*line.quantity,0);
 function locate(){if(!navigator.geolocation)return setError("Location services are not available on this device.");setLocating(true);setError("");navigator.geolocation.getCurrentPosition(({coords})=>{setCoordinates({latitude:coords.latitude,longitude:coords.longitude});setLocating(false)},()=>{setError("Allow location access, then try again.");setLocating(false)},{enableHighAccuracy:true,timeout:12000})}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:form.get("fullName"),phone:form.get("phone"),email:form.get("email"),fulfilmentMethod:method,deliveryAddress:form.get("deliveryAddress"),deliveryArea:form.get("deliveryArea"),deliveryLatitude:coordinates?.latitude,deliveryLongitude:coordinates?.longitude,items:lines.map(line=>({productId:line.product!.id,quantity:line.quantity}))})}),data=await response.json();if(!response.ok)return setError(data.error??"Unable to place order.");setComplete(data)}
 if(complete)return <main className="checkout-success"><CheckCircle2/><h1>Order received</h1><p>Your order <strong>{complete.orderNumber}</strong> has been sent to Healthfield Pharmacy. A confirmation email is on its way.</p><a href="/#products">Continue shopping</a></main>;
 return <main className="checkout-page"><header><a href="/#products"><ArrowLeft/> Shop</a><Image src="/healthfield-logo-clean.png" alt="Healthfield Pharmacy" width={210} height={75}/><a href={customer?"/account":"/login?next=/checkout"}>{customer?`Hi, ${customer.firstName}`:"Sign in"}</a></header><div className="checkout-layout"><form onSubmit={submit}><span className="auth-kicker">Secure checkout</span><h1>Delivery details</h1><div className="checkout-methods"><button type="button" className={method==="DELIVERY"?"active":""} onClick={()=>setMethod("DELIVERY")}><MapPin/> Home delivery</button><button type="button" className={method==="PICKUP"?"active":""} onClick={()=>setMethod("PICKUP")}><ShoppingCart/> Pickup</button></div><div className="checkout-fields"><label>Full name<input name="fullName" defaultValue={customer?`${customer.firstName} ${customer.lastName}`:""} required/></label><label>Phone number<input name="phone" defaultValue={customer?.phone??""} required/></label><label>Email address<input name="email" type="email" defaultValue={customer?.email??""}/></label><label>Town or area<input name="deliveryArea" required={method==="DELIVERY"}/></label>{method==="DELIVERY"&&<><label className="full">Delivery address<textarea name="deliveryAddress" rows={3} required/></label><div className="checkout-location full"><button type="button" onClick={locate} disabled={locating}><LocateFixed/>{locating?"Getting location…":coordinates?"Location captured":"Use my current location"}</button>{coordinates&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${coordinates.latitude},${coordinates.longitude}`}>Preview on Google Maps</a>}</div></>}</div><h2>Payment method</h2><label className="payment-choice"><input type="radio" defaultChecked name="payment" value="MPESA"/><CreditCard/><span><strong>M-Pesa</strong><small>Payment prompt after confirmation</small></span></label>{error&&<div className="auth-error">{error}</div>}<button className="place-order" disabled={!lines.length}>Place order</button></form><aside><h2>Order summary</h2>{lines.map(line=><article key={line.product!.id}><div><strong>{line.product!.name}</strong><small>{line.product!.packSize} · Qty {line.quantity}</small></div><span>KES {(Number(line.product!.discountPrice??line.product!.price)*line.quantity).toLocaleString()}</span></article>)}<div className="checkout-total"><span>Subtotal<b>KES {subtotal.toLocaleString()}</b></span><span>Delivery<b>KES {method==="DELIVERY"?"250":"0"}</b></span><span>Total<strong>KES {(subtotal+(method==="DELIVERY"?250:0)).toLocaleString()}</strong></span></div></aside></div></main>
}
